-- Sample tasks for pagination demo
INSERT INTO tasks (title, description, status, priority, due_date, created_at, updated_at) VALUES
('Setup project infrastructure', 'Initialize Spring Boot project with necessary dependencies', 'DONE', 'HIGH', '2025-10-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Design database schema', 'Create ERD and define tables for the application', 'DONE', 'HIGH', '2025-10-02', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Implement user authentication', 'Add JWT-based authentication system', 'IN_PROGRESS', 'HIGH', '2025-10-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Create REST API endpoints', 'Develop CRUD operations for tasks', 'DONE', 'MEDIUM', '2025-10-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Add pagination support', 'Implement pagination for task listing', 'DONE', 'MEDIUM', '2025-10-06', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Write unit tests', 'Add comprehensive unit tests for services', 'IN_PROGRESS', 'MEDIUM', '2025-10-12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Setup CI/CD pipeline', 'Configure GitHub Actions for automated deployment', 'OPEN', 'LOW', '2025-10-20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Implement filtering', 'Add status and priority filters to task list', 'DONE', 'MEDIUM', '2025-10-07', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Create API documentation', 'Generate Swagger/OpenAPI documentation', 'OPEN', 'LOW', '2025-10-18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Add error handling', 'Implement global exception handler', 'IN_PROGRESS', 'HIGH', '2025-10-11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Optimize database queries', 'Add indexes and optimize N+1 queries', 'OPEN', 'MEDIUM', '2025-10-15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Implement sorting', 'Add multi-field sorting capability', 'DONE', 'LOW', '2025-10-08', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Setup logging', 'Configure structured logging with SLF4J', 'DONE', 'LOW', '2025-10-04', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Add validation', 'Implement request validation with Bean Validation', 'DONE', 'MEDIUM', '2025-10-06', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Create frontend UI', 'Build React frontend for task management', 'IN_PROGRESS', 'HIGH', '2025-10-14', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Implement search functionality', 'Add full-text search for tasks', 'OPEN', 'MEDIUM', '2025-10-16', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Setup monitoring', 'Add health checks and metrics with Actuator', 'OPEN', 'LOW', '2025-10-22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Add CORS configuration', 'Configure CORS for frontend integration', 'DONE', 'MEDIUM', '2025-10-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Implement data export', 'Add CSV/Excel export functionality', 'OPEN', 'LOW', '2025-10-25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Write integration tests', 'Add end-to-end integration tests', 'OPEN', 'MEDIUM', '2025-10-17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Setup database migrations', 'Configure Flyway for database versioning', 'OPEN', 'LOW', '2025-10-19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Add rate limiting', 'Implement API rate limiting', 'OPEN', 'LOW', '2025-10-24', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Create admin panel', 'Build admin interface for user management', 'OPEN', 'MEDIUM', '2025-10-21', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Implement notifications', 'Add email notifications for task updates', 'OPEN', 'MEDIUM', '2025-10-23', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Performance testing', 'Run load tests and optimize bottlenecks', 'OPEN', 'HIGH', '2025-10-13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
